version: '3.7'

name: chat-app

volumes:
    logs:
        driver: local

services:
    slim:
        image: php
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        container_name: chat-app
