name: PHP Composer Running Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:80

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        docker-compose up -d

    - name: Validate composer.json and composer.lock
      run: docker-compose exec app composer validate --strict

    - name: Install dependencies
      run: docker-compose exec app composer install --prefer-dist --no-progress

    - name: Setup config.yml
      run: |
        docker-compose exec app cp src/Application/Config/auth-secret.yml src/Application/Config/config.yml

    - name: Run test suite
      run: docker-compose exec app composer test